### ISSUE TITLE
User needs to have a way to know the sampling period of the chime that they are connecting to

### ISSUE THREAD

**Issue by Jayway523** [udellc/Loom4Max#11]
Currently, packets are retrieved by count and we need to know how often they are recorded (minutes, hours, days, etc) to be able to have equivalent time periods between sensors.

"Solution: Be able to request samples from the last time period - specify number and unit (min, hr, days, weeks, yrs). This time-based request will need to run through a calculator where we request the last 3 samples and analyze their time stamps. Take the average delta change in time to determine the sample period. Then calculate how many samples need to be requested based on the calculated sample period and the total time duration requested.
UNLESS, there is a way to request MongoDB samples by referring to the timestamp field instead of the sample number field, which may be a better approach. 
NOTE: Even if you are querying data by timestamp - you still need to know how many data points in this period you have - to reference how far into the table we are playing through. e.g. playing the 100th sample of 500"

**Comment by udellc** [comment]
I saw a post here that looked promising. But looks like we need to be wrapping our data on the MongoDB side a certain way. https://www.mongodb.com/community/forums/t/finding-data-between-two-dates-by-using-a-query-in-mongodb-charts/102506/3

**Comment by EthanBar** [comment]
@Jayway523 implemented this, available as `samplingPeriodSeconds` in the mongoDB patcher
