### ISSUE TITLE
Node script not ready can't handle message connect

### ISSUE THREAD

**Issue by syedi-code** [udellc/Loom4Max#16]
When opening a patch that uses the MongoDB Connection Setup subpatch, the Max console will print "node.script: Node script not ready can't handle message connect" and the Connection Setup patch will be unable to communicate with MongoDB. Current workarounds include launching Max 8 in administrative mode on Windows devices or running "npm install" through the Windows terminal in the Max 8 installation folder.

**Comment by EthanBar** [comment]
I believe this is all fixed now?
